version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: "cypress/browsers:node16.14.0-chrome99-ff97"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Install dpkg and fakeroot
          command: |
            sudo apt-get update -y
            sudo dpkg --add-architecture i386 && sudo apt-get update -y
            sudo apt-get install -y dpkg fakeroot wine32 wine64 rpm
      - run:
          name: Generate Builds
          command: npm run dist
      - run:
          name: Check Directory
          path: ~/repo/
          command: ls
      - run:
          name: Check Dist Directory
          path: ~/repo/dist
          command: ls
      - run:
          name: Get LinuxJS
          command: npm i @mainsilent/linux.js --save-dev
      - run:
          name: Get LinuxJS Requirements
          command: npx reqs
      - run:
          name: Build ISO
          path: ~/repo/
          command: npx linuxjs

      - store_artifacts:
          path: ~/repo/dist