version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:14.17.4
    steps:
      - checkout
      - run:
          name: Install nodeJS dependencies
          command: npm i
      - run:
          name: Install other dependencies
          command: |
            sudo apt-get update -y
            sudo dpkg --add-architecture i386 && sudo apt-get update -y
            sudo apt-get install -y dpkg fakeroot wine32 wine64 rpm
            sudo apt-get install squashfs-tools
            sudo apt-get install genisoimage
            sudo apt-get install -y make
      - run:
          name: Build AppImage for ISO
          command: npm run dist && ls
      - run:
          name: Get LinuxJS
          path: ~/repo/
          command: npm i @mainsilent/linux.js --save-dev && sudo npx reqs && ls
      - run:
          name: Build ISO
          path: ~/repo/
          command: sudo npx linuxjs
      - persist_to_workspace:
          root: filesystem
          paths:
            - KasiusNextISO.iso

      - store_artifacts:
          path: ~/repo/filesystem/KasiusNextISO.iso
  
  publish-github-release:
    working_directory: ~/repo
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp/filesystem
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t "${GITHUB_TOKEN}" \
            -u "${CIRCLE_PROJECT_USERNAME}" \
            -r "${CIRCLE_PROJECT_REPONAME}" \
            -c "${CIRCLE_SHA1}" \
            v1.1.6 /tmp/filesystem

workflows:
  build_and_publish:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
