version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Install required tools
          command: |
            sudo apt-get update -y
            sudo dpkg --add-architecture i386 && sudo apt-get update -y
            sudo apt-get install -y dpkg fakeroot wine32 wine64 rpm && sudo apt-get install squashfs-tools && sudo apt-get install genisoimage && sudo apt-get install -y make && sudo ln -s /usr/bin/genisoimage /usr/bin/mkisofs
      - run:
          name: Generate Builds
          command: npm run dist && ls
      - run:
          name: Get LinuxJS
          path: ~/repo/
          command: npm i @mainsilent/linux.js --save-dev && sudo npx reqs && ls
      - run:
          name: Build ISO
          path: ~/repo/
          command: sudo npx linuxjs

      - store_artifacts:
          path: ~/repo/filesystem/KasiusNextISO.iso
  publish-github-release:
    working_directory: ~/repo
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run: ls
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t "${GITHUB_TOKEN}" \
            -u "${CIRCLE_PROJECT_USERNAME}" \
            -r "${CIRCLE_PROJECT_REPONAME}" \
            -c "${CIRCLE_SHA1}" \
            v1.0.0 ~/repo/filesystem/KasiusNextISO.iso

workflows:
  build_and_publish:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
